package src;

import com.toedter.calendar.JDateChooser;

import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;

public class CreateOrEdit extends JDialog {

    private JPanel mainPanel;
    private JTextField titleField;
    private JTextField descField;
    private JLabel priorityText;
    private JLabel deadlineText;
    private JComboBox priorityField;
    private JButton actionButton;
    private JDateChooser datePicker;

    private final TaskManager taskManager = new TaskManager();
    private final String titlePlaceholder = "Enter a title *";
    private final String descPlaceholder = "Enter a description";
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    private Task task;

    public CreateOrEdit(JFrame parentComponent, Task task) {
        super(parentComponent, getWindowTitle(task), true);
        this.task = task;

        $$$setupUI$$$();
        setContentPane(mainPanel);
        setSize(300, 200);
        setLocationRelativeTo(parentComponent);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        if (task == null) {
            actionButton.setText("Create");
            Placeholders.addPlaceholder(titleField, titlePlaceholder);
            Placeholders.addPlaceholder(descField, descPlaceholder);
        } else {
            actionButton.setText("Edit");
            loadTask();
        }

        actionButton.addActionListener(e -> saveTask());
    }

    private static String getWindowTitle(Task task) {
        if (task == null) {
            return "Create task";
        }
        return "Edit task";
    }

    private void createUIComponents() {
        datePicker = new JDateChooser();
        datePicker.setPreferredSize(new Dimension(125, 30));
    }

    private void loadTask() {
        titleField.setText(task.getTitle());
        descField.setText(task.getDescription());
        datePicker.setDate(java.sql.Date.valueOf(task.getDeadline()));
        priorityField.setSelectedItem(task.getPriority());
    }

    private void saveTask() {
        String title = titleField.getText().trim();
        if (title.isEmpty() || title.equals(titlePlaceholder)) {
            JOptionPane.showMessageDialog(this, "A title is required");
            return;
        }

        String description = descField.getText().trim();
        if (description.equals(descPlaceholder)) {
            description = "";
        }

        Date selectedDate = datePicker.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Please pick a deadline");
            return;
        }

        LocalDate deadline = new java.sql.Date(selectedDate.getTime()).toLocalDate();

        if (LocalDate.now().isAfter(deadline)) {
            JOptionPane.showMessageDialog(this, "The deadline cannot be past");
            return;
        }

        String priority = priorityField.getSelectedItem().toString();

        if (task == null) {
            Task newTask = new Task(title, description, deadline, Priority.valueOf(priority));
            taskManager.addTask(newTask);

        } else {
            task.setTitle(title);
            task.setDescription(description);
            task.setDeadline(deadline);
            task.setPriority(priority);
            taskManager.updateTask(task);
        }

        dispose();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
        titleField = new JTextField();
        titleField.setText("Enter a title *");
        mainPanel.add(titleField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        mainPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        descField = new JTextField();
        descField.setText("Enter a description");
        mainPanel.add(descField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        priorityText = new JLabel();
        priorityText.setText("Select a priority");
        mainPanel.add(priorityText, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        priorityField = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("low");
        defaultComboBoxModel1.addElement("medium");
        defaultComboBoxModel1.addElement("high");
        priorityField.setModel(defaultComboBoxModel1);
        mainPanel.add(priorityField, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deadlineText = new JLabel();
        deadlineText.setText("Select a deadline");
        mainPanel.add(deadlineText, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        mainPanel.add(datePicker, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        actionButton = new JButton();
        actionButton.setText("Button");
        mainPanel.add(actionButton, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}